### ISSUE TITLE
Doesn't work with Dailymotion playlists

### ISSUE THREAD

**Issue by mzso** [sebaro/SaveTube#2]
Savetube doesn't appear for the selected video.

eg:
http://www.dailymotion.com/playlist/x3lo55_rswinkey_assassin-s-creed-black-flag-hd-1080p-60fps/1#video=x2f19hu

**Comment by sebaro** [comment]
Playlists are not supported because there's no way to know when the current video finishes playing and when the next one starts.

I can only make the script work for the current/first video or redirect the playlist URL to the current/first video page.

Or you can open the videos from the playlists in a new window/tab.
